const Validator = require('jsonschema').Validator;
const animationSchema = require('./docs/json/animation/animation.json');
const booleanSchema = require('./docs/json/helpers/int-boolean.json');
const transformSchema = require('./docs/json/helpers/transform.json');
const blendModeSchema = require('./docs/json/constants/blend-mode.json');
const lineCapSchema = require('./docs/json/constants/line-cap.json');
const lineJoinSchema = require('./docs/json/constants/linejoin.json');
const compositeSchema = require('./docs/json/constants/composite.json');
const textCapsSchema = require('./docs/json/constants/text-caps.json');
const textJustificationSchema = require('./docs/json/constants/text-justify.json');
const layerShapeSchema = require('./docs/json/layers/shape-layer.json');
const layerImageSchema = require('./docs/json/layers/image-layer.json');
const layerNullSchema = require('./docs/json/layers/null-layer.json');
const layerPreCompSchema = require('./docs/json/layers/precomposition-layer.json');
const layerSolidSchema = require('./docs/json/layers/solid-layer.json');
const layerTextSchema = require('./docs/json/layers/text-layer.json');
const shapeEllipseSchema = require('./docs/json/shapes/ellipse.json');
const shapeFillSchema = require('./docs/json/shapes/fill.json');
const shapeGFillSchema = require('./docs/json/shapes/gradient-fill.json');
const shapeGroupSchema = require('./docs/json/shapes/group.json');
const shapeGStrokeSchema = require('./docs/json/shapes/gradient-stroke.json');
const shapeMergeSchema = require('./docs/json/shapes/merge.json');
const shapeRectSchema = require('./docs/json/shapes/rectangle.json');
const shapeRepeaterSchema = require('./docs/json/shapes/repeater.json');
const shapeRoundSchema = require('./docs/json/shapes/rounded-corners.json');
const shapeShapeSchema = require('./docs/json/shapes/path.json');
const shapeStarSchema = require('./docs/json/shapes/polystar.json');
const shapeStrokeSchema = require('./docs/json/shapes/stroke.json');
const shapeTransformSchema = require('./docs/json/shapes/transform.json');
const shapeTrimSchema = require('./docs/json/shapes/trim.json');
const doubleKeyframeSchema = require('./docs/json/animated-properties/keyframe.json');
const multiDimensionalSchema = require('./docs/json/animated-properties/multi-dimensional.json');
const multiDimensionalKeyframedSchema = require('./docs/json/animated-properties/animated-property.json');
const multiDimensionalSpatialKeyframedSchema = require('./docs/json/animated-properties/position.json');
const offsetKeyframeSchema = require('./docs/json/animated-properties/position-keyframe.json');
const offsetSpatialKeyframeSchema = require('./docs/json/animated-properties/position=keyframe.json');
const shapeSchema = require('./docs/json/animated-properties/shape-property.json');
const shapeKeyframedSchema = require('./docs/json/animated-properties/shape-keyframe.json');
const shapePropSchema = require('./docs/json/animated-properties/shape-property.json');
const shapePropKeyframeSchema = require('./docs/json/animated-properties/shape-keyframe.json');
const valueSchema = require('./docs/json/animated-properties/value.json');
const valueKeyframeSchema = require('./docs/json/animated-properties/keyframe.json');
const valueKeyframedSchema = require('./docs/json/animated-properties/animated-property.json');
const gradientSchema = require('./docs/json/animated-properties/gradient-colors.json');
const imageSourceSchema = require('./docs/json/assets/image.json');
const preCompSourceSchema = require('./docs/json/assets/precomposition.json');
const charSourceSchema = require('./docs/json/text/character-data.json');

var v = new Validator();
v.addSchema(booleanSchema, '/#/$defs/helpers/int-boolean.json');
v.addSchema(transformSchema, '/#/$defs/helpers/transform.json');
v.addSchema(blendModeSchema, '/#/$defs/constants/blend-mode.json');
v.addSchema(lineCapSchema, '/#/$defs/constants/line-cap.json');
v.addSchema(lineJoinSchema, '/#/$defs/constants/linejoin.json');
v.addSchema(compositeSchema, '/#/$defs/constants/composite.json');
v.addSchema(textCapsSchema, '/#/$defs/constants/text-caps.json');
v.addSchema(textJustificationSchema, '/#/$defs/constants/text-justify.json');
v.addSchema(layerShapeSchema, '/#/$defs/layers/shape-layer.json');
v.addSchema(layerImageSchema, '/#/$defs/layers/image-layer.json');
v.addSchema(layerNullSchema, '/#/$defs/layers/null-layer.json');
v.addSchema(layerPreCompSchema, '/#/$defs/layers/precomposition-layer.json');
v.addSchema(layerSolidSchema, '/#/$defs/layers/solid-layer.json');
v.addSchema(layerTextSchema, '/#/$defs/layers/text-layer.json');
v.addSchema(shapeEllipseSchema, '/#/$defs/shapes/ellipse.json');
v.addSchema(shapeFillSchema, '/#/$defs/shapes/fill.json');
v.addSchema(shapeGFillSchema, '/#/$defs/shapes/gradient-fill.json');
v.addSchema(shapeGroupSchema, '/#/$defs/shapes/group.json');
v.addSchema(shapeGStrokeSchema, '/#/$defs/shapes/gradient-stroke.json');
v.addSchema(shapeMergeSchema, '/#/$defs/shapes/merge.json');
v.addSchema(shapeRectSchema, '/#/$defs/shapes/rectangle.json');
v.addSchema(shapeRepeaterSchema, '/#/$defs/shapes/repeater.json');
v.addSchema(shapeRoundSchema, '/#/$defs/shapes/rounded-corners.json');
v.addSchema(shapeShapeSchema, '/#/$defs/shapes/path.json');
v.addSchema(shapeStarSchema, '/#/$defs/shapes/polystar.json');
v.addSchema(shapeStrokeSchema, '/#/$defs/shapes/stroke.json');
v.addSchema(shapeTransformSchema, '/#/$defs/shapes/transform.json');
v.addSchema(shapeTrimSchema, '/#/$defs/shapes/trim.json');
v.addSchema(doubleKeyframeSchema, '/#/$defs/animated-properties/keyframe.json');
v.addSchema(multiDimensionalSchema, '/#/$defs/animated-properties/multi-dimensional.json');
v.addSchema(multiDimensionalKeyframedSchema, '/#/$defs/animated-properties/animated-property.json');
v.addSchema(multiDimensionalSpatialKeyframedSchema, '/#/$defs/animated-properties/position.json');
v.addSchema(offsetKeyframeSchema, '/#/$defs/animated-properties/position-keyframe.json');
v.addSchema(offsetSpatialKeyframeSchema, '/#/$defs/animated-properties/position=keyframe.json');
v.addSchema(shapeSchema, '/#/$defs/animated-properties/shape-property.json');
v.addSchema(shapeKeyframedSchema, '/#/$defs/animated-properties/shape-keyframe.json');
v.addSchema(shapePropSchema, '/#/$defs/animated-properties/shape-property.json');
v.addSchema(shapePropKeyframeSchema, '/#/$defs/animated-properties/shape-keyframe.json');
v.addSchema(valueSchema, '/#/$defs/animated-properties/value.json');
v.addSchema(valueKeyframeSchema, '/#/$defs/animated-properties/keyframe.json');
v.addSchema(valueKeyframedSchema, '/#/$defs/animated-properties/animated-property.json');
v.addSchema(gradientSchema, '/#/$defs/animated-properties/gradient-colors.json');
v.addSchema(imageSourceSchema, '/#/$defs/assets/image.json');
v.addSchema(preCompSourceSchema, '/#/$defs/assets/precomposition.json');
v.addSchema(charSourceSchema, '/#/$defs/text/character-data.json');

function validate(animation) {
  return v.validate(animation, animationSchema, {nestedErrors: true});
}

module.exports = validate;
